name: 🐞 Informe de error (Cuando usas)
description: Reportar un problema o posible error al usar `chatgpt-demon`
labels: ['pending triage', 'use']
body:
  - type: markdown
    attributes:
      value: |
        ### Antes de enviar...
        ¡Gracias por tomarse el tiempo para completar este informe de error! Por favor, confirme los siguientes puntos antes de submitting:

        ✅ He comprobado que el error aún no se ha informado al buscar en GitHub bajo problemas.
        ✅ Usa el inglés para hacer preguntas. Esto permite que más personas busquen y participen en el tema.
  - type: input
    id: os
    attributes:
      label: Qué sistema operativo estás usando?
      placeholder: Mac, Windows, Linux
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: ¿Qué navegador estás usando?
      placeholder: Chrome, Firefox, Safari
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describa el error
      description: Una descripción clara y concisa de lo que es el error.
      placeholder: Descripción del error
    validations:
      required: true
  - type: textarea
    id: prompt
    attributes:
      label: ¿Qué indicación ingresaste?
      description: Si el problema está relacionado con el mensaje que ingresó, complete este campo.
  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Verifique su navegador y complete el mensaje de error si existe.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: Estoy dispuesto a enviar una solicitud de extracción para este problema.
          required: false