name: 🐞 Informe de error (Cuando se autodespliega)
description: Informe un problema o un posible error cuando implemente en su propio servidor o en la nube.
labels: ['pending triage', 'deploy']
body:
  - type: markdown
    attributes:
      value: |
        ### Antes de enviar...
        ¡Gracias por tomarse el tiempo para completar este informe de error! Por favor, confirme los siguientes puntos antes de submitting:

        ✅ estoy usando **última versión de chatgpt-demon**. 
        ✅ He comprobado que el error aún no se ha informado al buscar en GitHub bajo problemas.
        ✅ Usa el inglés para hacer preguntas. Esto permite que más personas busquen y participen en el tema.
  - type: dropdown
    id: server
    attributes:
      label: ¿Cómo se despliega Anse?
      description: Seleccione el método de implementación utilizado.
      options:
        - Node
        - Docker
        - Vercel
        - Netlify
        - Railway
        - Others (Specify in description)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describa el error
      description: A descripción clara y concisa de lo que es el error.
      placeholder: Descripción del error
    validations:
      required: true
  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Verifique su navegador y la consola del nodo, complete el mensaje de error si existe.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: Estoy dispuesto a enviar una solicitud de extracción para este problema.
          required: false