blank_issues_enabled: false
contact_links:
  - name:  Discusiones
    url: https://github.com/ElChema-Nc/ChatGpt-Demon/issues
    about: Use discusiones si tiene una idea para mejorar o para hacer preguntas.
