name:  Solicitud de función
description: Sugerir una característica o una mejora
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        ### Antes de enviar...
        ¡Gracias por tomarse el tiempo para completar esta solicitud de función! Por favor, confirme los siguientes puntos antes submitting:

         Verifiqué que la función no se haya enviado ya al buscar en GitHub en problemas o discusiones.
         Usa el inglés. Esto permite que más personas busquen y participen en el tema.
  - type: textarea
    id: feature-description
    attributes:
      label: Describa la característica
      description: Una descripción clara y concisa de lo que cree que sería una adición útil.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: Estoy dispuesto a enviar una solicitud de incorporación de cambios para esta función.
          required: false
